splash = false

wallpaper {
    monitor = eDP-1
    # path = /home/alex/Downloads/zenitsu-agatsuma-3840x2160-19143.jpg
    path = /home/alex/Downloads/Picture/wall_secondary.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1 
    path = /home/alex/Downloads/zenitsu-agatsuma-3840x2160-19143.jpg
    fit_mode = cover
}



# preload = /home/alex/Downloads/820178.jpg
# wallpaper = eDP-1,/home/alex/Downloads/820178.jpg
# wallpaper = HDMI-A-1,/home/alex/Downloads/820178.jpg
