#!/usr/bin/env bash

set -euo pipefail


runllama=$(curl http://localhost:8080/v1/chat/completions \
    -H 'Content-Type: application/json' \
    -d '{
        "model": "TheStageAI/Qwen3.5-9B-GGUF:Q4_K_M",
        "messages": [
        {"role": "user", "content": "Can you create a heartbreak quote for me?"}
        ],
        "max_tokens": 1000,
        "chat_template_kwargs": {
            "enable_thinking": false
        }
}' | jq -r '.choices[0].message.content')

echo "$runllama" | wl-copy
notify-send "$runllama"


